force-app/main/default/objects/Affiliation__c/Affiliation__c.object-meta.xml
<CustomObject>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Affiliation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliation__c/fields/Horse__c.field-meta.xml
<CustomField>
    <fullName>Horse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Horse</label>
    <referenceTo>Horse__c</referenceTo>
    <relationshipLabel>Related Accounts</relationshipLabel>
    <relationshipName>Related_Horses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affiliation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Horse__c/Horse__c.object-meta.xml
<CustomObject>
    <description>This represents an individual Horse.</description>
    <label>Horse</label>
    <nameField>
        <displayFormat>H-{00000}</displayFormat>
        <label>Horse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Horses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Horse__c/fields/IsCompeting__c.field-meta.xml
<CustomField>
    <fullName>IsCompeting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Competing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AffiliationQuery.cls
public with sharing class AffiliationQuery {
    @InvocableMethod(label='Query Affiliation Records by Lead Id and Competing Horse')
    public static List<Integer> queryAffiliations(List<String> leadIds) {
        Integer count = [SELECT COUNT() 
                         FROM Affiliation__c 
                         WHERE Lead__c IN :leadIds AND Horse__r.IsCompeting__c = true];
        return new List<Integer>{ count };
    }
}