force-app/main/default/objects/Horse__c/Horse__c.object-meta.xml
<CustomObject>
    <description>This represents an individual Horse.</description>
    <label>Horse</label>
    <nameField>
        <displayFormat>H-{00000}</displayFormat>
        <label>Horse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Horses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Horse__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stallion</fullName>
            </value>
            <value>
                <fullName>Mare</fullName>
            </value>
            <value>
                <fullName>Gelding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SampleLookupController.cls
public with sharing class SampleLookupController {
    private final static Integer MAX_RESULTS = 5;

    @AuraEnabled(cacheable=true scope='global')
    public static List<LookupSearchResult> search(String searchTerm, List<String> selectedIds) {
        system.debug('IN SEARCH()');
        system.debug('search term: '+ searchTerm);
        // Prepare query parameters
        searchTerm += '*';

        // Execute search query
        List<List<SObject>> searchResults = [
            FIND :searchTerm
            IN ALL FIELDS
            RETURNING
                Horse__c(Id, Name__c, Registration_Number__c, Gender__c WHERE id NOT IN :selectedIds)
            LIMIT :MAX_RESULTS
        ];

        // Prepare results
        List<LookupSearchResult> results = new List<LookupSearchResult>();

        // Extract Horses & convert them into LookupSearchResult
        String horseIcon = 'custom:custom47';
        Horse__c[] horses = (List<Horse__c>) searchResults[0];
        for (Horse__c horse : horses) {
            String subtitle = horse.Gender__c + ' • ' + horse.Registration_Number__c;
            results.add(new LookupSearchResult(horse.Id, 'Horse', horseIcon, horse.Name__c, subtitle));
        }

        // Optionnaly sort all results on title
        results.sort();

        return results;
    }
}